services:
  - type: web
    name: telegram-news-render-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: FINAL_LINE
        value: '<a href="https://t.me/gameplusbackstage">GP Backstage</a> | #новости'
      - key: MEDIA_TIMEOUT
        value: "0.9"
